In [2]:
import pandas as pd 
list1 = [[1,'Prashant',1000], [2,'Arun',2000]]

df = pd.DataFrame(list1)
df

   0         1     2
0  1  Prashant  1000
1  2      Arun  2000

In [3]:
df.columns = ["1","2","3"]

In [4]:
df

   1         2     3
0  1  Prashant  1000
1  2      Arun  2000

In [7]:
df["3"] = df["3"] * 2

In [1]:
import pandas as pd

df = pd.DataFrame({
    "eid":   [1, 2, 3, 3, 4, 5],
    "ename": ["Prashant", "Amar", "Chitra", "Chitra", "Utkarsha", "Ajit"],
    "esal":  [1000, 2000, 2000, 2000, 9878, 9999]
})

df

   eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    3    Chitra  2000
4    4  Utkarsha  9878
5    5      Ajit  9999

In [2]:
df

   eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    3    Chitra  2000
4    4  Utkarsha  9878
5    5      Ajit  9999

In [3]:
deptList = ['HR','Ops','','','Ops','HR']

df["department"] = pd.Series(deptList)

In [4]:
# Use-case: I want to create a new column called UpdatedYearlySalary based on the following increment/hike conditions
# If the salary is less than equal to 1500, then inc the sal by 10%
# If the salary is between 1501 and 10000, then inc the sal by 5%
# If the salary is between 10001 and 20000, then inc the sal by 2.5%
# If the salary is greater than 20000 , then no inc

In [6]:
def yearlysalary(salary):
    if salary <= 1500:
        salary = salary * 1.10
    elif salary >= 1501 and salary <= 10000:
        salary = salary * 1.05
    elif salary >= 10001 and salary <= 2000:
        salary = salary * 1.025
    elif salary > 2000:
        salary = salary 
    return salary

In [8]:
df["yearlyupdatedsalary"] = df.esal.apply(yearlysalary)

In [10]:
df

   eid     ename  esal department  yearlyupdatedsalary
0    1  Prashant  1000         HR              1100.00
1    2      Amar  2000        Ops              2100.00
2    3    Chitra  2000                         2100.00
3    3    Chitra  2000                         2100.00
4    4  Utkarsha  9878        Ops             10371.90
5    5      Ajit  9999         HR             10498.95

In [11]:
import pandas as pd

df = pd.DataFrame({
    "eid": [1, 2, 3, 3, 4, 5],
    "ename": ["Prashant", "Amar", "Chitra", "Chitra", "Utkarsha", "Ajit"],
    "esal": [1000, 2000, 2000, 2000, 9878, 9999],
    "yearlySalary": [12000, 24000, 24000, 24000, 118536, 119988],
    "department": ["HR", "Ops", "Admin", "Admin", "Ops", "HR"],
    "UpdatedSalary": [1100.00, 2100.00, 2100.00, 2100.00, 10371.90, 10498.95],
    "UpdatedYearlySalary": [13200.0, 25200.0, 25200.0, 25200.0, 124462.8, 125987.4]
})

df

,eid,ename,esal,yearlySalary,department,UpdatedSalary,UpdatedYearlySalary
0,1,Prashant,1000,12000,HR,1100.00,13200.0
1,2,Amar,2000,24000,Ops,2100.00,25200.0
2,3,Chitra,2000,24000,Admin,2100.00,25200.0
3,3,Chitra,2000,24000,Admin,2100.00,25200.0
4,4,Utkarsha,9878,118536,Ops,10371.90,124462.8
5,5,Ajit,9999,119988,HR,10498.95,125987.4

In [21]:
df[(df.esal > 5000) & (df.department == "Ops")]

,eid,ename,esal,yearlySalary,department,UpdatedSalary,UpdatedYearlySalary
4,4,Utkarsha,9878,118536,Ops,10371.9,124462.8

In [26]:
df[(df.department == "HR") & (df.esal > 6500)].ename

5    Ajit
Name: ename, dtype: object

In [27]:
df.drop_duplicates(inplace = True)

In [28]:
df

,eid,ename,esal,yearlySalary,department,UpdatedSalary,UpdatedYearlySalary
0,1,Prashant,1000,12000,HR,1100.00,13200.0
1,2,Amar,2000,24000,Ops,2100.00,25200.0
2,3,Chitra,2000,24000,Admin,2100.00,25200.0
4,4,Utkarsha,9878,118536,Ops,10371.90,124462.8
5,5,Ajit,9999,119988,HR,10498.95,125987.4

In [40]:
dfExample1 = pd.DataFrame([[4,'QA'],[1,'HR'],[3,'Dev'],[2,'Ops']] , columns=['eid','dept'])

In [41]:
dfExample2 = pd.DataFrame([[1,'Prashant'],[2,'Gokul'],[3,'Guna']] , columns=['empid','ename'])

In [46]:
pd.merge(dfExample1,dfExample2, right_on = "empid", left_on = "eid")

   eid dept  empid     ename
0    1   HR      1  Prashant
1    3  Dev      3      Guna
2    2  Ops      2     Gokul

In [47]:
import pandas as pd

df = pd.DataFrame({
    "patient_id": [1, 2, 3, 4, 5, 6],
    "gender": ["M", "F", "F", "M", "F", "M"],
    "cancer_type": ["A", "A", "B", "B", "A", "B"],
    "survival_days": [200, 350, 400, 150, 500, 300]
})

df

   patient_id gender cancer_type  survival_days
0           1      M           A            200
1           2      F           A            350
2           3      F           B            400
3           4      M           B            150
4           5      F           A            500
5           6      M           B            300

In [48]:
df.groupby("cancer_type")["survival_days"].mean()

cancer_type
A    350.000000
B    283.333333
Name: survival_days, dtype: float64

In [49]:
df.groupby("cancer_type")["survival_days"].agg(["mean", "median", "count"])

                   mean  median  count
cancer_type
A            350.000000   350.0      3
B            283.333333   300.0      3

In [50]:
df.groupby(["cancer_type", "gender"])["survival_days"].mean()

cancer_type  gender
A            F         425.0
             M         200.0
B            F         400.0
             M         225.0
Name: survival_days, dtype: float64

In [51]:
df.groupby("cancer_type")["survival_days"].mean().reset_index()

  cancer_type  survival_days
0           A     350.000000
1           B     283.333333

In [58]:
avg_survival = df.groupby("cancer_type")["survival_days"].mean()
avg_survival[avg_survival > 300]

cancer_type
A    350.0
Name: survival_days, dtype: float64

In [59]:
import pandas as pd

df = pd.DataFrame({
    "patient_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "gender": ["M", "F", "F", "M", "F", "M", "F", "M"],
    "cancer_type": ["A", "A", "B", "B", "A", "B", "A", "B"],
    "age": [45, 62, 70, 55, 38, 80, 66, 50],
    "survival_days": [300, 420, 150, 280, 500, 120, 390, 260]
})

df

   patient_id gender cancer_type  age  survival_days
0           1      M           A   45            300
1           2      F           A   62            420
2           3      F           B   70            150
3           4      M           B   55            280
4           5      F           A   38            500
5           6      M           B   80            120
6           7      F           A   66            390
7           8      M           B   50            260

In [61]:
df.groupby(["cancer_type"])["survival_days"].mean()

cancer_type
A    402.5
B    202.5
Name: survival_days, dtype: float64

In [65]:
df.groupby(["cancer_type","gender"])["survival_days"].mean()

cancer_type  gender
A            F         436.666667
             M         300.000000
B            F         150.000000
             M         220.000000
Name: survival_days, dtype: float64

In [66]:
df.groupby(["cancer_type","gender"])["survival_days"].mean().reset_index()

  cancer_type gender  survival_days
0           A      F     436.666667
1           A      M     300.000000
2           B      F     150.000000
3           B      M     220.000000

In [67]:
def elder_age(Age):
    if Age >= 65:
        return 1
    else:
        return 0
df["elderly"] = df["age"].apply(elder_age)

In [73]:
df.groupby(["elderly"])["survival_days"].mean().reset_index()

   elderly  survival_days
0        0          352.0
1        1          220.0

In [75]:
patients = pd.DataFrame({
    "patient_id": [1, 2, 3, 4],
    "age": [45, 62, 70, 55],
    "gender": ["M", "F", "F", "M"]
})
visits = pd.DataFrame({
    "patient_id": [1, 2, 2, 3],
    "hospital": ["A", "B", "C", "A"],
    "cost": [1000, 2000, 1500, 1800]
})