In [2]:
import pandas as pd 
list1 = [[1,'Prashant',1000], [2,'Arun',2000]]

df = pd.DataFrame(list1)
df

   0         1     2
0  1  Prashant  1000
1  2      Arun  2000

In [3]:
df.columns = ["1","2","3"]

In [4]:
df

   1         2     3
0  1  Prashant  1000
1  2      Arun  2000

In [7]:
df["3"] = df["3"] * 2

In [1]:
import pandas as pd

df = pd.DataFrame({
    "eid":   [1, 2, 3, 3, 4, 5],
    "ename": ["Prashant", "Amar", "Chitra", "Chitra", "Utkarsha", "Ajit"],
    "esal":  [1000, 2000, 2000, 2000, 9878, 9999]
})

df

   eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    3    Chitra  2000
4    4  Utkarsha  9878
5    5      Ajit  9999

In [2]:
df

   eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    3    Chitra  2000
4    4  Utkarsha  9878
5    5      Ajit  9999

In [3]:
deptList = ['HR','Ops','','','Ops','HR']

df["department"] = pd.Series(deptList)

In [4]:
# Use-case: I want to create a new column called UpdatedYearlySalary based on the following increment/hike conditions
# If the salary is less than equal to 1500, then inc the sal by 10%
# If the salary is between 1501 and 10000, then inc the sal by 5%
# If the salary is between 10001 and 20000, then inc the sal by 2.5%
# If the salary is greater than 20000 , then no inc

In [6]:
def yearlysalary(salary):
    if salary <= 1500:
        salary = salary * 1.10
    elif salary >= 1501 and salary <= 10000:
        salary = salary * 1.05
    elif salary >= 10001 and salary <= 2000:
        salary = salary * 1.025
    elif salary > 2000:
        salary = salary 
    return salary

In [8]:
df["yearlyupdatedsalary"] = df.esal.apply(yearlysalary)

In [10]:
df

   eid     ename  esal department  yearlyupdatedsalary
0    1  Prashant  1000         HR              1100.00
1    2      Amar  2000        Ops              2100.00
2    3    Chitra  2000                         2100.00
3    3    Chitra  2000                         2100.00
4    4  Utkarsha  9878        Ops             10371.90
5    5      Ajit  9999         HR             10498.95

In [11]:
import pandas as pd

df = pd.DataFrame({
    "eid": [1, 2, 3, 3, 4, 5],
    "ename": ["Prashant", "Amar", "Chitra", "Chitra", "Utkarsha", "Ajit"],
    "esal": [1000, 2000, 2000, 2000, 9878, 9999],
    "yearlySalary": [12000, 24000, 24000, 24000, 118536, 119988],
    "department": ["HR", "Ops", "Admin", "Admin", "Ops", "HR"],
    "UpdatedSalary": [1100.00, 2100.00, 2100.00, 2100.00, 10371.90, 10498.95],
    "UpdatedYearlySalary": [13200.0, 25200.0, 25200.0, 25200.0, 124462.8, 125987.4]
})

df

,eid,ename,esal,yearlySalary,department,UpdatedSalary,UpdatedYearlySalary
0,1,Prashant,1000,12000,HR,1100.00,13200.0
1,2,Amar,2000,24000,Ops,2100.00,25200.0
2,3,Chitra,2000,24000,Admin,2100.00,25200.0
3,3,Chitra,2000,24000,Admin,2100.00,25200.0
4,4,Utkarsha,9878,118536,Ops,10371.90,124462.8
5,5,Ajit,9999,119988,HR,10498.95,125987.4

In [21]:
df[(df.esal > 5000) & (df.department == "Ops")]

,eid,ename,esal,yearlySalary,department,UpdatedSalary,UpdatedYearlySalary
4,4,Utkarsha,9878,118536,Ops,10371.9,124462.8

In [26]:
df[(df.department == "HR") & (df.esal > 6500)].ename

5    Ajit
Name: ename, dtype: object

In [27]:
df.drop_duplicates(inplace = True)

In [28]:
df

,eid,ename,esal,yearlySalary,department,UpdatedSalary,UpdatedYearlySalary
0,1,Prashant,1000,12000,HR,1100.00,13200.0
1,2,Amar,2000,24000,Ops,2100.00,25200.0
2,3,Chitra,2000,24000,Admin,2100.00,25200.0
4,4,Utkarsha,9878,118536,Ops,10371.90,124462.8
5,5,Ajit,9999,119988,HR,10498.95,125987.4

In [40]:
dfExample1 = pd.DataFrame([[4,'QA'],[1,'HR'],[3,'Dev'],[2,'Ops']] , columns=['eid','dept'])

In [41]:
dfExample2 = pd.DataFrame([[1,'Prashant'],[2,'Gokul'],[3,'Guna']] , columns=['empid','ename'])

In [46]:
pd.merge(dfExample1,dfExample2, right_on = "empid", left_on = "eid")

   eid dept  empid     ename
0    1   HR      1  Prashant
1    3  Dev      3      Guna
2    2  Ops      2     Gokul

In [47]:
import pandas as pd

df = pd.DataFrame({
    "patient_id": [1, 2, 3, 4, 5, 6],
    "gender": ["M", "F", "F", "M", "F", "M"],
    "cancer_type": ["A", "A", "B", "B", "A", "B"],
    "survival_days": [200, 350, 400, 150, 500, 300]
})

df

   patient_id gender cancer_type  survival_days
0           1      M           A            200
1           2      F           A            350
2           3      F           B            400
3           4      M           B            150
4           5      F           A            500
5           6      M           B            300

In [48]:
df.groupby("cancer_type")["survival_days"].mean()

cancer_type
A    350.000000
B    283.333333
Name: survival_days, dtype: float64

In [49]:
df.groupby("cancer_type")["survival_days"].agg(["mean", "median", "count"])

                   mean  median  count
cancer_type
A            350.000000   350.0      3
B            283.333333   300.0      3

In [50]:
df.groupby(["cancer_type", "gender"])["survival_days"].mean()

cancer_type  gender
A            F         425.0
             M         200.0
B            F         400.0
             M         225.0
Name: survival_days, dtype: float64

In [51]:
df.groupby("cancer_type")["survival_days"].mean().reset_index()

  cancer_type  survival_days
0           A     350.000000
1           B     283.333333

In [58]:
avg_survival = df.groupby("cancer_type")["survival_days"].mean()
avg_survival[avg_survival > 300]

cancer_type
A    350.0
Name: survival_days, dtype: float64

In [59]:
import pandas as pd

df = pd.DataFrame({
    "patient_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "gender": ["M", "F", "F", "M", "F", "M", "F", "M"],
    "cancer_type": ["A", "A", "B", "B", "A", "B", "A", "B"],
    "age": [45, 62, 70, 55, 38, 80, 66, 50],
    "survival_days": [300, 420, 150, 280, 500, 120, 390, 260]
})

df

   patient_id gender cancer_type  age  survival_days
0           1      M           A   45            300
1           2      F           A   62            420
2           3      F           B   70            150
3           4      M           B   55            280
4           5      F           A   38            500
5           6      M           B   80            120
6           7      F           A   66            390
7           8      M           B   50            260

In [61]:
df.groupby(["cancer_type"])["survival_days"].mean()

cancer_type
A    402.5
B    202.5
Name: survival_days, dtype: float64

In [65]:
df.groupby(["cancer_type","gender"])["survival_days"].mean()

cancer_type  gender
A            F         436.666667
             M         300.000000
B            F         150.000000
             M         220.000000
Name: survival_days, dtype: float64

In [66]:
df.groupby(["cancer_type","gender"])["survival_days"].mean().reset_index()

  cancer_type gender  survival_days
0           A      F     436.666667
1           A      M     300.000000
2           B      F     150.000000
3           B      M     220.000000

In [67]:
def elder_age(Age):
    if Age >= 65:
        return 1
    else:
        return 0
df["elderly"] = df["age"].apply(elder_age)

In [73]:
df.groupby(["elderly"])["survival_days"].mean().reset_index()

   elderly  survival_days
0        0          352.0
1        1          220.0

In [75]:
patients = pd.DataFrame({
    "patient_id": [1, 2, 3, 4],
    "age": [45, 62, 70, 55],
    "gender": ["M", "F", "F", "M"]
})
visits = pd.DataFrame({
    "patient_id": [1, 2, 2, 3],
    "hospital": ["A", "B", "C", "A"],
    "cost": [1000, 2000, 1500, 1800]
})

In [ ]:
groupby operations

In [1]:
import pandas as pd

df = pd.DataFrame([
    {"order_id": 101, "cust_id": "C1", "city": "Dallas",  "order_dt": "2026-01-02", "channel": "web",    "category": "protein", "sku": "chicken", "qty": 2, "unit_price": 6.50, "discount": 1.00, "returned": 0},
    {"order_id": 101, "cust_id": "C1", "city": "Dallas",  "order_dt": "2026-01-02", "channel": "web",    "category": "protein", "sku": "tofu",    "qty": 3, "unit_price": 2.00, "discount": 0.00, "returned": 0},
    {"order_id": 102, "cust_id": "C1", "city": "Dallas",  "order_dt": "2026-01-03", "channel": "store",  "category": "coffee",  "sku": "arabica", "qty": 1, "unit_price": 12.0, "discount": 2.00, "returned": 0},
    {"order_id": 103, "cust_id": "C2", "city": "Austin",  "order_dt": "2026-01-03", "channel": "web",    "category": "protein", "sku": "paneer",  "qty": 1, "unit_price": 5.00, "discount": 0.50, "returned": 1},
    {"order_id": 104, "cust_id": "C2", "city": "Austin",  "order_dt": "2026-01-05", "channel": "store",  "category": "coffee",  "sku": "robusta", "qty": 2, "unit_price": 8.00, "discount": 0.00, "returned": 0},
    {"order_id": 105, "cust_id": "C3", "city": "Corpus",  "order_dt": "2026-01-05", "channel": "web",    "category": "protein", "sku": "soy",     "qty": 5, "unit_price": 1.50, "discount": 1.00, "returned": 0},
    {"order_id": 106, "cust_id": "C3", "city": "Corpus",  "order_dt": "2026-01-06", "channel": "web",    "category": "coffee",  "sku": "arabica", "qty": 1, "unit_price": 12.0, "discount": 0.00, "returned": 1},
    {"order_id": 107, "cust_id": "C3", "city": "Corpus",  "order_dt": "2026-01-06", "channel": "store",  "category": "protein", "sku": "chicken", "qty": 1, "unit_price": 7.00, "discount": 0.00, "returned": 0},
    {"order_id": 108, "cust_id": "C4", "city": "Dallas",  "order_dt": "2026-01-06", "channel": "web",    "category": "coffee",  "sku": "robusta", "qty": 3, "unit_price": 8.00, "discount": 4.00, "returned": 0},
    {"order_id": 109, "cust_id": "C4", "city": "Dallas",  "order_dt": "2026-01-07", "channel": "store",  "category": "protein", "sku": "tofu",    "qty": 2, "unit_price": 2.25, "discount": 0.25, "returned": 0},
])
df["order_dt"] = pd.to_datetime(df["order_dt"])
df["revenue"] = df["qty"] * df["unit_price"] - df["discount"]

df

,order_id,cust_id,city,order_dt,channel,category,sku,qty,unit_price,discount,returned,revenue
0,101,C1,Dallas,2026-01-02,web,protein,chicken,2,6.50,1.00,0,12.00
1,101,C1,Dallas,2026-01-02,web,protein,tofu,3,2.00,0.00,0,6.00
2,102,C1,Dallas,2026-01-03,store,coffee,arabica,1,12.00,2.00,0,10.00
3,103,C2,Austin,2026-01-03,web,protein,paneer,1,5.00,0.50,1,4.50
4,104,C2,Austin,2026-01-05,store,coffee,robusta,2,8.00,0.00,0,16.00
5,105,C3,Corpus,2026-01-05,web,protein,soy,5,1.50,1.00,0,6.50
6,106,C3,Corpus,2026-01-06,web,coffee,arabica,1,12.00,0.00,1,12.00
7,107,C3,Corpus,2026-01-06,store,protein,chicken,1,7.00,0.00,0,7.00
8,108,C4,Dallas,2026-01-06,web,coffee,robusta,3,8.00,4.00,0,20.00
9,109,C4,Dallas,2026-01-07,store,protein,tofu,2,2.25,0.25,0,4.25

In [8]:
df.groupby(["category"])["qty"].()

category
coffee     1.5
protein    2.0
Name: qty, dtype: float64

In [24]:
df.groupby(["cust_id"])["order_id"].count()

cust_id
C1    3
C2    2
C3    3
C4    2
Name: order_id, dtype: int64

In [27]:
df.groupby(["city"])["revenue"].sum()

city
Austin    20.50
Corpus    25.50
Dallas    52.25
Name: revenue, dtype: float64

In [2]:
df_returned_excluded = df[df["returned"] == 0]
df_returned_excluded

,order_id,cust_id,city,order_dt,channel,category,sku,qty,unit_price,discount,returned,revenue
0,101,C1,Dallas,2026-01-02,web,protein,chicken,2,6.50,1.00,0,12.00
1,101,C1,Dallas,2026-01-02,web,protein,tofu,3,2.00,0.00,0,6.00
2,102,C1,Dallas,2026-01-03,store,coffee,arabica,1,12.00,2.00,0,10.00
4,104,C2,Austin,2026-01-05,store,coffee,robusta,2,8.00,0.00,0,16.00
5,105,C3,Corpus,2026-01-05,web,protein,soy,5,1.50,1.00,0,6.50
7,107,C3,Corpus,2026-01-06,store,protein,chicken,1,7.00,0.00,0,7.00
8,108,C4,Dallas,2026-01-06,web,coffee,robusta,3,8.00,4.00,0,20.00
9,109,C4,Dallas,2026-01-07,store,protein,tofu,2,2.25,0.25,0,4.25

In [3]:
df_returned_excluded.groupby(["cust_id"])["revenue"].sum()

cust_id
C1    28.00
C2    16.00
C3    13.50
C4    24.25
Name: revenue, dtype: float64

In [4]:
df.groupby(["order_id"])["qty"].mean()

order_id
101    2.5
102    1.0
103    1.0
104    2.0
105    5.0
106    1.0
107    1.0
108    3.0
109    2.0
Name: qty, dtype: float64

Merge

In [2]:
customers = pd.DataFrame([
    {"cust_id": "C1", "cust_name": "Harsha", "segment": "Gold"},
    {"cust_id": "C2", "cust_name": "Rahul",  "segment": "Silver"},
    {"cust_id": "C3", "cust_name": "Anita",  "segment": "Gold"},
    {"cust_id": "C5", "cust_name": "Kiran",  "segment": "Bronze"},  # not in orders
])
customers

  cust_id cust_name segment
0      C1    Harsha    Gold
1      C2     Rahul  Silver
2      C3     Anita    Gold
3      C5     Kiran  Bronze

In [3]:
orders = pd.DataFrame({
    "order_id": [1, 2, 3],
    "cust_id": ["C1", "C2", "C3"]
})

In [4]:
orders

   order_id cust_id
0         1      C1
1         2      C2
2         3      C3

In [14]:
orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4],
    "cust_id": ["C1", "C2", "C3", "C1"],
    "amount": [100, 200, 150, 50]
})
orders

   order_id cust_id  amount
0         1      C1     100
1         2      C2     200
2         3      C3     150
3         4      C1      50

In [15]:
customers = pd.DataFrame({
    "cust_id": ["C1", "C2"],
    "cust_name": ["Alice", "Bob"]
})
customers

  cust_id cust_name
0      C1     Alice
1      C2       Bob

In [18]:
pd.merge(orders,customers,on = "cust_id", how = "left")

   order_id cust_id  amount cust_name
0         1      C1     100     Alice
1         2      C2     200       Bob
2         3      C3     150       NaN
3         4      C1      50     Alice

In [20]:
orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5],
    "cust_id": ["C1", "C2", "C3", "C1", "C4"],
    "sku": ["A", "B", "A", "C", "B"],
    "qty": [2, 1, 3, 1, 2]
})
customers = pd.DataFrame({
    "cust_id": ["C1", "C2", "C3"],
    "cust_name": ["Alice", "Bob", "Charlie"]
})
products = pd.DataFrame({
    "sku": ["A", "B"],
    "price": [10, 20]
})

display(orders,customers,products)

   order_id cust_id sku  qty
0         1      C1   A    2
1         2      C2   B    1
2         3      C3   A    3
3         4      C1   C    1
4         5      C4   B    2

  cust_id cust_name
0      C1     Alice
1      C2       Bob
2      C3   Charlie

  sku  price
0   A     10
1   B     20

In [28]:
df2 = pd.merge(orders,customers, on = "cust_id",how = "left")
df3 = pd.merge(df2,products, on = "sku", how = "right")

In [34]:
df["qty"] = df["qty"].astype("float64")

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    10 non-null     int64
 1   cust_id     10 non-null     object
 2   city        10 non-null     object
 3   order_dt    10 non-null     datetime64[ns]
 4   channel     10 non-null     object
 5   category    10 non-null     object
 6   sku         10 non-null     object
 7   qty         10 non-null     float64
 8   unit_price  10 non-null     float64
 9   discount    10 non-null     float64
 10  returned    10 non-null     int64
 11  revenue     10 non-null     float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(5)
memory usage: 1.1+ KB

In [41]:
jan = pd.DataFrame({
    "order_id": [1, 2],
    "amount": [100, 200]
})
feb = pd.DataFrame({
    "order_id": [3, 4],
    "amount": [150, 300]
})

pd.concat([jan,feb],ignore_index = True)

   order_id  amount
0         1     100
1         2     200
2         3     150
3         4     300

In [42]:
dataTable = pd.DataFrame([[1000],[2000],[3000],[4000],[5000],[6000],[7000],[8000],[9000],[2000000]] , columns=['sal'])
dataTable1 = pd.DataFrame([[1000],[2000],[3000],[4000],[5000],[6000],[7000],[8000],[9000],[10000]] , columns=['sal'])

In [46]:
display(dataTable.describe(),dataTable1.describe())

                sal
count  1.000000e+01
mean   2.045000e+05
std    6.308797e+05
min    1.000000e+03
25%    3.250000e+03
50%    5.500000e+03
75%    7.750000e+03
max    2.000000e+06

                sal
count     10.000000
mean    5500.000000
std     3027.650354
min     1000.000000
25%     3250.000000
50%     5500.000000
75%     7750.000000
max    10000.000000